version: "3.1"
services:
  web:
    container_name: odoo16
    image: odoo:16
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons-customize:/mnt/extra-addons-customize
      - ./enterprise:/mnt/enterprise-addons
    stdin_open: true
    tty: true
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo

volumes:
  odoo-web-data:
  postgres_data:
